package nmd.orb.error;

/**
 * Author : Igor Usenko ( igors48@gmail.com )
 * Date : 29.06.13
 */
public enum ErrorCode {

    UNHANDLED_EXCEPTION,

    URL_FETCH_ERROR,

    FEED_EXPORT_ERROR,

    FEED_PARSE_ERROR,

    WRONG_FEED_ID,
    WRONG_FEED_TASK_ID,
    WRONG_CATEGORY_ID,

    NO_SCHEDULED_TASK,

    INVALID_FEED_ID,
    INVALID_FEED_TITLE,
    INVALID_FEED_DESCRIPTION,
    INVALID_FEED_URL,
    INVALID_URL,

    INVALID_ITEM_ID,
    INVALID_ITEM_TITLE,
    INVALID_ITEM_DESCRIPTION,
    INVALID_ITEM_LINK,
    INVALID_ITEM_GOTO_LINK,
    INVALID_ITEM_DATE,

    INVALID_CATEGORY_NAME,
    INVALID_CATEGORY_ID,

    INVALID_FEED_OR_ITEM_ID,
    INVALID_MARK_MODE,
    CATEGORY_ALREADY_EXISTS,
    INVALID_SIZE,
    INVALID_PARAMETERS_COUNT,
    INVALID_DIRECTION,

    INSTAGRAM_NO_META,
    INSTAGRAM_WRONG_STATUS_CODE,
    INSTAGRAM_NO_USERS,
    INSTAGRAM_USER_NOT_FOUND,
    INSTAGRAM_BAD_DATA_LINK,
    INSTAGRAM_BAD_DATA_TYPE,
    INSTAGRAM_NO_IMAGES,
    INSTAGRAM_NO_DATA,

    INVALID_IMPORT_FILE,

    FEED_IMPORT_JOB_STARTED_ALREADY,
    FEED_IMPORT_JOB_INVALID_ACTION,

    MAIL_SERVICE_ERROR

}
