package nmd.rss.collector.error;

/**
 * Author : Igor Usenko ( igors48@gmail.com )
 * Date : 29.06.13
 */
public enum ErrorCode {

    UNHANDLED_EXCEPTION,
    URL_FETCH_ERROR,
    FEED_EXPORT_ERROR,
    FEED_PARSE_ERROR,
    WRONG_FEED_ID,
    INVALID_FEED_ID,
    INVALID_FEED_TITLE,
    INVALID_FEED_OR_ITEM_ID,
    INVALID_MARK_MODE,
    WRONG_FEED_TASK_ID,
    NO_SCHEDULED_TASK,
    UNKNOWN_CATEGORY,
    CATEGORY_ALREADY_EXISTS,
    INVALID_CATEGORY_NAME,
    INVALID_FEED_URL,
    INVALID_CATEGORY_ID

}
